### ISSUE TITLE
Getting error in combination with MMM-Modulebar

### ISSUE THREAD

**Issue by BlueForrest** [eckonator/MMM-YouLess2#1]
When I installed MMM-Modulebar I'm getting "Undefined" message on the mirrorscreen for the Youless2 module.
Looking into the mirror dev tools I see this error information: (I don't know how to fix this.)

`TypeError: wrapper.gaugeMeter is not a function
    at Class.getDom (:8080/modules/MMM-YouLess2/MMM-YouLess2.js:78)
    at main.js:113
    at new Promise (<anonymous>)
    at updateDom (main.js:111)
    at main.js:53
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20)
    at Object.modulesStarted (main.js:502)
    at startModules (loader.js:55)
    at loader.js:38

MMM-YouLess2.js:78 Uncaught (in promise) TypeError: wrapper.gaugeMeter is not a function
    at Class.getDom (:8080/modules/MMM-YouLess2/MMM-YouLess2.js:78)
    at main.js:113
    at new Promise (<anonymous>)
    at updateDom (main.js:111)
    at main.js:53
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20)
    at Object.modulesStarted (main.js:502)
    at startModules (loader.js:55)
    at loader.js:38 `

**Comment by eckonator** [comment]
Looks like the GaugeMeter.js is not found. Have you done a „npm install“ after checkout this modul repo?

**Comment by BlueForrest** [comment]
Hello Markus,
Yes I've done the npm install, but it gave me some errors (5 moderate, 1
high, 1 critical)  - So I executed 'npm audit' to get more detail.

 *High          │ Regular Expression Denial of Service in tough-cookie
    │*
│ Package       │ tough-cookie
    │
│ Patched in    │ >=2.3.3
   │
│ Dependency of │ request
   │
│ Path          │ request > tough-cookie
    │
│ More info     │ https://github.com/advisories/GHSA-g7q5-pjjr-gqvp


* Critical      │ Insufficient Entropy in cryptiles
   │*│ Package       │ cryptiles
         │
│ Patched in    │ >=4.1.2
   │
│ Dependency of │ request
   │
│ Path          │ request > hawk > cryptiles
    │
│ More info     │ https://github.com/advisories/GHSA-rq8g-5pc5-wrhr

I looked at those websites but I don't know how to fix these errors. What
exactly need to be installed. It's a bit like chinees for me.  (Sorry for
the expression)

I hope you can give me more details how to fix or solve this.
Thanks in advance
Kind regards,
Johan

**Comment by eckonator** [comment]
Difficult to help without watching the problem in your enviroment. It is possible to have a teamviewer session with you to debug your problem?

**Comment by BlueForrest** [comment]
Hello Markus,
I have installed Putty so I can remotely access the PI now.
Next I installed teamviewer on my laptop.

It's already a bit late now but if OK for you,  would it be possible to
connect tomorrow around 08 PM ?

Thanks.
Regards,
Johan

**Comment by eckonator** [comment]
Problem solved. The problem arose because this module and another module have 2x jQuery included. This caused a JavaScript error. We have now disabled the loading of jQuery in the other module.
